#!/usr/bin/env python3
"""Generate src/eval_fitted.h from a solver-space coefs file.

Input: 1242 lines of "j value" (j<621 -> MG, j>=621 -> EG) — the format
emitted by luminex-evaltrace --dump-coefs (current engine) and
solve_ridge.py (fitted candidates). Values are rounded to int (engine eval
is integer cp).

The generated header defines inline FE_MG[621] / FE_EG[621] in solver-index
space; evaluation.cpp + eval_trace.cpp reference features by feat:: index,
so applying a fit = regenerate this one header and rebuild.

Usage: python gen_fitted.py <coefs.txt> [src/eval_fitted.h]
"""
import sys

NPHASE = 621

# index -> label for readable output (sparse; unlabeled entries print bare)
LBL = {
    384: "MAT+pawn", 385: "MAT+knight", 386: "MAT+bishop", 387: "MAT+rook",
    388: "MAT+queen", 389: "MAT+king",
    456: "pawn_doubled", 457: "pawn_isolated", 479: "pawn_lever_c", 480: "pawn_backward",
    509: "pp_rook_behind", 510: "pp_enemy_rook", 511: "pp_king_prox", 512: "pp_unreach_s",
    513: "pp_unreach_b", 521: "pp_stop_own", 522: "pp_stop_att",
    540: "trapped_n", 541: "far_n", 542: "far_b", 550: "bish_long", 551: "outpost_b",
    552: "rook_open", 553: "rook_semi", 554: "rook_7th", 555: "rook_xray_q", 556: "far_r",
    557: "rook_trap_c", 558: "rook_trap_nc", 559: "rook_blocked", 560: "far_q",
    561: "shield_r1", 562: "shield_r2", 563: "shield_r3", 564: "open_kfile", 565: "open_adj",
    566: "storm", 567: "castled", 568: "nocastle", 594: "hang_pawn", 595: "hang_piece",
    596: "pinned", 597: "space_own", 598: "space_opp", 599: "imbal_const", 600: "imbal_pawn",
    601: "bishop_pair", 602: "knight_pawn", 603: "tradedown", 604: "ks_au",
    605: "ks_flight1", 606: "ks_flight2", 607: "rook_pawn", 608: "nn_pair",
    609: "nb_pair", 610: "shield_kf_r1", 611: "shield_kf_r2", 612: "shield_kf_r3",
    613: "shield_adj_r1", 614: "shield_adj_r2", 615: "shield_adj_r3",
    616: "shield_ext_r1", 617: "shield_ext_r2", 618: "shield_ext_r3",
    619: "hole_kf", 620: "hole_adj",
}


def main():
    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/eval_fitted.h"
    vals = [0.0] * (2 * NPHASE)
    with open(src) as fh:
        for ln in fh:
            if not ln.strip():
                continue
            j, v = ln.split()
            vals[int(j)] = float(v)
    mg = [int(round(vals[j])) for j in range(NPHASE)]
    eg = [int(round(vals[NPHASE + j])) for j in range(NPHASE)]

    def block(name, arr):
        out = [f"inline int {name}[{NPHASE}] = {{"]
        for base in range(0, NPHASE, 8):
            cells = []
            for j in range(base, min(base + 8, NPHASE)):
                tag = f" /*{LBL[j]}*/" if j in LBL else ""
                cells.append(f"{arr[j]:>6d},{tag}")
            out.append("    " + " ".join(cells))
        out.append("};")
        return "\n".join(out)

    with open(dst, "w") as fh:
        fh.write("// GENERATED by gen_fitted.py from " + src + " -- do not edit by hand.\n")
        fh.write("// FE_MG/FE_EG: current coefficient of every eval feature, solver-index space\n")
        fh.write("// (see eval_feat.h). evaluation.cpp and eval_trace.cpp both read these, so\n")
        fh.write("// --verify revalidates the engine against whatever fit is applied here.\n")
        fh.write("#pragma once\n\nnamespace luminex {\n\n")
        fh.write(block("FE_MG", mg) + "\n\n")
        fh.write(block("FE_EG", eg) + "\n\n")
        fh.write("} // namespace luminex\n")
    print(f"wrote {dst}: mg[{min(mg)}..{max(mg)}] eg[{min(eg)}..{max(eg)}]")


if __name__ == "__main__":
    main()
